"""CAN protocol definitions and message codecs."""

from .enums import ControlMode, FaultSeverity
from .ids import (
    ARM_CONTROL_COMMAND_ID,
    ARM_DIAG_RESPONSE_ID,
    ARM_FAULT_STATUS_ID,
    ARM_STATUS_FEEDBACK_ID,
    CONTROL_COMMAND_ID,
    DIAG_RESPONSE_ID,
    FAULT_STATUS_ID,
    HAND_CONTROL_COMMAND_ID,
    HAND_DIAG_RESPONSE_ID,
    HAND_FAULT_STATUS_ID,
    HAND_STATUS_FEEDBACK_ID,
    STATUS_FEEDBACK_ID,
)
from .messages import (
    ARM_CONTROL_DLC,
    ARM_DIAG_DLC,
    ARM_FAULT_DLC,
    ARM_STATUS_DLC,
    HAND_CONTROL_DLC,
    HAND_DIAG_DLC,
    HAND_FAULT_DLC,
    HAND_STATUS_DLC,
    ArmControlCommand,
    ArmDiagResponse,
    ArmFaultStatus,
    ArmStatusFeedback,
    HandControlCommand,
    HandDiagResponse,
    HandFaultStatus,
    HandStatusFeedback,
    JointControlCommand,
    JointDiagResponse,
    JointFaultStatus,
    JointStatusFeedback,
)

__all__ = [
    "ControlMode",
    "FaultSeverity",
    "HAND_CONTROL_COMMAND_ID",
    "HAND_STATUS_FEEDBACK_ID",
    "HAND_FAULT_STATUS_ID",
    "HAND_DIAG_RESPONSE_ID",
    "ARM_CONTROL_COMMAND_ID",
    "ARM_STATUS_FEEDBACK_ID",
    "ARM_FAULT_STATUS_ID",
    "ARM_DIAG_RESPONSE_ID",
    "CONTROL_COMMAND_ID",
    "STATUS_FEEDBACK_ID",
    "FAULT_STATUS_ID",
    "DIAG_RESPONSE_ID",
    "HAND_CONTROL_DLC",
    "HAND_STATUS_DLC",
    "HAND_FAULT_DLC",
    "HAND_DIAG_DLC",
    "ARM_CONTROL_DLC",
    "ARM_STATUS_DLC",
    "ARM_FAULT_DLC",
    "ARM_DIAG_DLC",
    "HandControlCommand",
    "HandStatusFeedback",
    "HandFaultStatus",
    "HandDiagResponse",
    "ArmControlCommand",
    "ArmStatusFeedback",
    "ArmFaultStatus",
    "ArmDiagResponse",
    "JointControlCommand",
    "JointStatusFeedback",
    "JointFaultStatus",
    "JointDiagResponse",
]
