"""CAN FD message identifiers used by RobotCAN."""

from .messages import (
    ARM_CONTROL_COMMAND_ID,
    ARM_DIAG_RESPONSE_ID,
    ARM_FAULT_STATUS_ID,
    ARM_STATUS_FEEDBACK_ID,
    HAND_CONTROL_COMMAND_ID,
    HAND_DIAG_RESPONSE_ID,
    HAND_FAULT_STATUS_ID,
    HAND_STATUS_FEEDBACK_ID,
)

CONTROL_COMMAND_ID = HAND_CONTROL_COMMAND_ID
STATUS_FEEDBACK_ID = HAND_STATUS_FEEDBACK_ID
FAULT_STATUS_ID = HAND_FAULT_STATUS_ID
DIAG_RESPONSE_ID = HAND_DIAG_RESPONSE_ID

__all__ = [
    "HAND_CONTROL_COMMAND_ID",
    "HAND_STATUS_FEEDBACK_ID",
    "HAND_FAULT_STATUS_ID",
    "HAND_DIAG_RESPONSE_ID",
    "ARM_CONTROL_COMMAND_ID",
    "ARM_STATUS_FEEDBACK_ID",
    "ARM_FAULT_STATUS_ID",
    "ARM_DIAG_RESPONSE_ID",
    "CONTROL_COMMAND_ID",
    "STATUS_FEEDBACK_ID",
    "FAULT_STATUS_ID",
    "DIAG_RESPONSE_ID",
]
